#!/bin/bash
set -e
export TEST_OUTPUT_INDENT_LVL=1
export order_file_name="order.descr"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/../tests # tests dir in repo
while IFS= read -r folder
do
	echo " ---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---*---"
	echo "[T] Executing test-module $folder"
	while IFS= read -r sub_folder
	do
		# run the sub-module test
		full_path=$folder/$sub_folder
		if [[ -f $full_path/test-descr.bash ]]; then
			set +e
			(./run-test-module.sh $full_path $full_path $SCRIPT_DIR/..) && (echo -n -e ' \t '; echo "[t] sub-test $sub_folder done") || (echo -n -e ' \t '; echo "[t] sub-test $sub_folder done (NOT successful)")
			set -e
			echo
		fi
	done < $folder/$order_file_name
	echo "[T] Done test-module $folder"
	echo
done < $order_file_name
